version: '3.7'

services:
  web_server:
    container_name: textima-web-server
    build:
      dockerfile: ../web-server.Dockerfile
      context: ./web-server
    image: dzubape/textima-web-server
    ports:
      - ${WEB_PORT}:${WEB_SERVER_PORT}
    volumes:
      - ./web-server:/app/dev
    working_dir: /app/${TAG}
    env_file: .env
    restart: always
    # profiles: ["backend"]

  storage:
    container_name: textima-storage
    build:
      dockerfile: ../storage.Dockerfile
      context: ./storage
      args:
        STORAGE_SERVER_PORT: ${STORAGE_SERVER_PORT}
    image: dzubape/textima/storage
    env_file: .env
    volumes:
      - ./storage:/app/dev
      # - ./datasets:/app/storage
      - /home/petro/dev/sci-pyter/sandbox/xubean:/app/storage
    working_dir: /app/${TAG}
    restart: always
    # profiles: ["backend"]

  # web_client:
  #   container_name: web-client
  #   build:
  #     dockerfile: ../web-client.Dockerfile
  #     context: ./web-client
  #   image: dzubape/textima/web-client
  #   env_file: .env
  #   restart: "no"
  #   depends_on:
  #     - web_server
  #     - storage
  #   profiles: ["frontend"]

