version: '3.7'

services:
  web:
    container_name: textima-web
    build:
      dockerfile: ./web.Dockerfile
      target: ${TAG}
      context: ./
    image: dzubape/textima/web:${TAG}
    ports:
      - ${WEB_PORT}:8080
    restart: always

    volumes:
      - ./:/app/dev

  storage:
    container_name: textima-storage
    build:
      dockerfile: ../storage.Dockerfile
      target: ${TAG}
      context: ./storage
    image: dzubape/textima/storage:${TAG}
    restart: always

    volumes:
      - ./storage:/app/dev
      - ../textima-storage:/app/storage
